kind: pipeline
name: TzPro-Go Pipeline
platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - pull_request
#  paths:
#    include:
#      - README.md

environment:
  CGO_ENABLED: 0

steps:
- name: run linter
  image: golangci/golangci-lint:v1.45-alpine
  commands:
    - golangci-lint run

- name: scan the files
  image: aquasec/trivy:0.24.3
  commands:
    - trivy fs --exit-code 1 --security-checks vuln,config ./
    - trivy config --exit-code 1 ./

- name: go build
  image: golang:1.19.0-alpine3.16
  commands:
    - go vet ./...
    - go test ./...
    - go build ./examples/...
